# Generated by Django 3.2.6 on 2021-09-30 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_number', models.AutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(max_length=25)),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('mobile_number', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='owner',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankClient.account')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankClient.client')),
            ],
        ),
    ]
